# Data Cleaning

Hey Ivette and Julia! As we discussed, I specifically loaded the bank-full.csv file and took the following steps for cleaning:


*   Checked for NA values (there were none to remove)
*   Converted all categorical variables to numeric
*   Defined X_bank_full and y_bank_full as features and target subsets of the bank_full dataframe

I figured for each algorithm I would let each of us do our own training and test set split, unless there's a good reason for us to use the same split. Let me know if I can answer any questions!

-Emmet

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
# From: https://archive.ics.uci.edu/dataset/222/bank+marketing
!pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.11/dist-packages (from ucimlrepo) (2025.1.31)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

In [7]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
bank_marketing = fetch_ucirepo(id=222)

# data (as pandas dataframes)
X = bank_marketing.data.features
y = bank_marketing.data.targets

# metadata
print(bank_marketing.metadata)

# variable information
print(bank_marketing.variables)

{'uci_id': 222, 'name': 'Bank Marketing', 'repository_url': 'https://archive.ics.uci.edu/dataset/222/bank+marketing', 'data_url': 'https://archive.ics.uci.edu/static/public/222/data.csv', 'abstract': 'The data is related with direct marketing campaigns (phone calls) of a Portuguese banking institution. The classification goal is to predict if the client will subscribe a term deposit (variable y).', 'area': 'Business', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 45211, 'num_features': 16, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Occupation', 'Marital Status', 'Education Level'], 'target_col': ['y'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2014, 'last_updated': 'Fri Aug 18 2023', 'dataset_doi': '10.24432/C5K306', 'creators': ['S. Moro', 'P. Rita', 'P. Cortez'], 'intro_paper': {'ID': 277, 'type': 'NATIVE', 'title': 'A data-driven approach to predict the success of bank telemarketing', 'authors': 'Sérgio Moro, P. Cortez, P. Rita', 'venue': 'Decision Support Systems', 'year': 2014, 'journal': None, 'DOI': '10.1016/j.dss.2014.03.001', 'URL': 'https://www.semanticscholar.org/paper/cab86052882d126d43f72108c6cb41b295cc8a9e', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': "The data is related with direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed. \n\nThere are four datasets: \n1) bank-additional-full.csv with all examples (41188) and 20 inputs, ordered by date (from May 2008 to November 2010), very close to the data analyzed in [Moro et al., 2014]\n2) bank-additional.csv with 10% of the examples (4119), randomly selected from 1), and 20 inputs.\n3) bank-full.csv with all examples and 17 inputs, ordered by date (older version of this dataset with less inputs). \n4) bank.csv with 10% of the examples and 17 inputs, randomly selected from 3 (older version of this dataset with less inputs). \nThe smallest datasets are provided to test more computationally demanding machine learning algorithms (e.g., SVM). \n\nThe classification goal is to predict if the client will subscribe (yes/no) a term deposit (variable y).", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Input variables:\n   # bank client data:\n   1 - age (numeric)\n   2 - job : type of job (categorical: "admin.","unknown","unemployed","management","housemaid","entrepreneur","student",\n                                       "blue-collar","self-employed","retired","technician","services") \n   3 - marital : marital status (categorical: "married","divorced","single"; note: "divorced" means divorced or widowed)\n   4 - education (categorical: "unknown","secondary","primary","tertiary")\n   5 - default: has credit in default? (binary: "yes","no")\n   6 - balance: average yearly balance, in euros (numeric) \n   7 - housing: has housing loan? (binary: "yes","no")\n   8 - loan: has personal loan? (binary: "yes","no")\n   # related with the last contact of the current campaign:\n   9 - contact: contact communication type (categorical: "unknown","telephone","cellular") \n  10 - day: last contact day of the month (numeric)\n  11 - month: last contact month of year (categorical: "jan", "feb", "mar", ..., "nov", "dec")\n  12 - duration: last contact duration, in seconds (numeric)\n   # other attributes:\n  13 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)\n  14 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric, -1 means client was not previously contacted)\n  15 - previous: number of contacts performed before this campaign and for this client (numeric)\n  16 - poutcome: outcome of the previous marketing campaign (categorical: "unknown","other","failure","success")\n\n  Output variable (desired target):\n  17 - y - has the client subscribed a term deposit? (binary: "yes","no")\n', 'citation': None}}
           name     role         type      demographic  \
0           age  Feature      Integer              Age
1           job  Feature  Categorical       Occupation
2       marital  Feature  Categorical   Marital Status
3     education  Feature  Categorical  Education Level
4       default  Feature       Binary             None
5       balance  Feature      Integer             None
6       housing  Feature       Binary             None
7          loan  Feature       Binary             None
8       contact  Feature  Categorical             None
9   day_of_week  Feature         Date             None
10        month  Feature         Date             None
11     duration  Feature      Integer             None
12     campaign  Feature      Integer             None
13        pdays  Feature      Integer             None
14     previous  Feature      Integer             None
15     poutcome  Feature  Categorical             None
16            y   Target       Binary             None

                                          description  units missing_values
0                                                None   None             no
1   type of job (categorical: 'admin.','blue-colla...   None             no
2   marital status (categorical: 'divorced','marri...   None             no
3   (categorical: 'basic.4y','basic.6y','basic.9y'...   None             no
4                              has credit in default?   None             no
5                              average yearly balance  euros             no
6                                   has housing loan?   None             no
7                                  has personal loan?   None             no
8   contact communication type (categorical: 'cell...   None            yes
9                        last contact day of the week   None             no
10  last contact month of year (categorical: 'jan'...   None             no
11   last contact duration, in seconds (numeric). ...   None             no
12  number of contacts performed during this campa...   None             no
13  number of days that passed by after the client...   None            yes
14  number of contacts performed before this campa...   None             no
15  outcome of the previous marketing campaign (ca...   None            yes
16          has the client subscribed a term deposit?   None             no

In [9]:
import pandas as pd

In [10]:
bank_full = pd.read_csv('/content/drive/MyDrive/Coursework 2025 WIN/IMT 574/Assignments/bank+marketing/bank/bank-full.csv', sep = ';')
print(bank_full.head())

   age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no
1   44    technician   single  secondary      no       29     yes   no
2   33  entrepreneur  married  secondary      no        2     yes  yes
3   47   blue-collar  married    unknown      no     1506     yes   no
4   33       unknown   single    unknown      no        1      no   no

   contact  day month  duration  campaign  pdays  previous poutcome   y
0  unknown    5   may       261         1     -1         0  unknown  no
1  unknown    5   may       151         1     -1         0  unknown  no
2  unknown    5   may        76         1     -1         0  unknown  no
3  unknown    5   may        92         1     -1         0  unknown  no
4  unknown    5   may       198         1     -1         0  unknown  no

In [11]:
# Count NA/NULL values in each column (code from: https://www.geeksforgeeks.org/how-to-count-the-number-of-nan-values-in-pandas/)
column_nan_count = bank_full.isna().sum()
print("NaN count per column:")
print(column_nan_count)

# Appears to be no NA/NULL values in bank_full

NaN count per column:
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [12]:
# Identify unique labels in categorical columns
for column in list(bank_full.columns):
  unique_values= bank_full[str(column)].unique()
  print('Unique values in ' + str(column) + ':' + str(unique_values))

Unique values in age:[58 44 33 47 35 28 42 43 41 29 53 57 51 45 60 56 32 25 40 39 52 46 36 49
 59 37 50 54 55 48 24 38 31 30 27 34 23 26 61 22 21 20 66 62 83 75 67 70
 65 68 64 69 72 71 19 76 85 63 90 82 73 74 78 80 94 79 77 86 95 81 18 89
 84 87 92 93 88]
Unique values in job:['management' 'technician' 'entrepreneur' 'blue-collar' 'unknown'
 'retired' 'admin.' 'services' 'self-employed' 'unemployed' 'housemaid'
 'student']
Unique values in marital:['married' 'single' 'divorced']
Unique values in education:['tertiary' 'secondary' 'unknown' 'primary']
Unique values in default:['no' 'yes']
Unique values in balance:[ 2143    29     2 ...  8205 14204 16353]
Unique values in housing:['yes' 'no']
Unique values in loan:['no' 'yes']
Unique values in contact:['unknown' 'cellular' 'telephone']
Unique values in day:[ 5  6  7  8  9 12 13 14 15 16 19 20 21 23 26 27 28 29 30  2  3  4 11 17
 18 24 25  1 10 22 31]
Unique values in month:['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'jan' 'feb' 'mar' 'apr' 'sep']
Unique values in duration:[ 261  151   76 ... 1298 1246 1556]
Unique values in campaign:[ 1  2  3  5  4  6  7  8  9 10 11 12 13 19 14 24 16 32 18 22 15 17 25 21
 43 51 63 41 26 28 55 50 38 23 20 29 31 37 30 46 27 58 33 35 34 36 39 44]
Unique values in pdays:[ -1 151 166  91  86 143 147  89 140 176 101 174 170 167 195 165 129 188
 196 172 118 119 104 171 117 164 132 131 123 159 186 111 115 116 173 178
 110 152  96 103 150 175 193 181 185 154 145 138 126 180 109 158 168  97
 182 127 130 194 125 105 102  26 179  28 183 155 112 120 137 124 187 190
 113 162 134 169 189   8 144 191 184 177   5  99 133  93  92  10 100 156
 198 106 153 146 128   7 121 160 107  90  27 197 136 139 122 157 149 135
  30 114  98 192 163  34  95 141  31 199  94 108  29 268 247 253 226 244
 239 245 204 231 238 258 230 254 265  71 223 246 250 266 240 205 261 259
 241 260 234 251 225 161 237 262 248 255 220 227 206 224 249 235 228 263
   2 270 232 252 207 200 269 233 256 273 272 242 264 208 214 222 271 203
 221 202 216 201 257 229 210 217  75 213  73  76 267 211 215  77 236  82
   6 209 274   1 243 212 275  80 276   9 279  12 280  88 277  85  84 219
  24  21 282  41 294  49 329 307 303 331 308 300  64 314 287 330 332 302
 323 318 333  60 326 335 313 312 305 325 327 336 309 328 322  39 316 292
 295 310 306 320 317 289  57 321 142 339 301 315 337 334 340 319  17  74
 148 341 299 344 342 324 345 346 304 281 343 338  14 347  15 291 348 349
 285 350 284  25 283 278  81   4  87  83  79  70  13 293  37  78  63  22
 296 355  66  19  35 360 357 354 351 362 358 365 298 286 364 363  47 361
 288 366 356 352 359 297 367 353 368  42 290  67 371 370 369  50  36 373
 374 372 311 375 378  59 379  40  18  43  20  69  38 385  56  55  44 391
  72 390  32  62 399 393  65 377 395 388 389 386  61 412 405 434 394 382
 459 440 397 383  68 461 462 463 422  51 457 430 442 403 454 428 392 410
 401 474 475 477 478  54 476 380 479  45  46 495  58  48 518  52 515 520
 511 536 387 218  33 544 435 436 555 433 446 558 469 616 561 553 384 592
 467 585 480 421 667 626 426 595 381 376 648 521 452 449 633 398  53 460
 670 551 414 557 687 404 651 686 425 504 578 674 416 586 411 756 450 745
 514 417 424 776 396 683 529 439 415 456 407 458 532 481 791 701 531 792
 413 445 535 784 419 455 491 431 542 470 472 717 437   3 782 728 828 524
 562 761 492 775 579 493 464 760 466 465 656 831 490 432 655 427 749 838
 769 587 778 854 779 850 771 594 842 589 603 484 489 486 409 444 680 808
 485 503 690 772 774 526 420 528 500 826 804 508 547 805 541 543 871 550
 530]
Unique values in previous:[  0   3   1   4   2  11  16   6   5  10  12   7  18   9  21   8  14  15
  26  37  13  25  20  27  17  23  38  29  24  51 275  22  19  30  58  28
  32  40  55  35  41]
Unique values in poutcome:['unknown' 'failure' 'other' 'success']
Unique values in y:['no' 'yes']

In [13]:
# Convert categorical variables with integers
bank_full['job'].replace(['admin.', 'blue-collar', 'entrepreneur', 'housemaid',
                          'management', 'retired', 'self-employed', 'services',
                          'student', 'technician', 'unemployed', 'unknown'],
                           [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], inplace=True)
bank_full['marital'].replace(['single', 'married', 'divorced'],[1, 2, 3], inplace=True)
bank_full['education'].replace(['tertiary', 'secondary', 'unknown', 'primary'],[3, 2, 0, 1], inplace=True)
bank_full['default'].replace(['no', 'yes'], [0, 1], inplace=True)
bank_full['housing'].replace(['yes', 'no'], [1, 0], inplace=True)
bank_full['loan'].replace(['no', 'yes'], [0, 1], inplace=True)
bank_full['contact'].replace(['unknown', 'cellular', 'telephone'], [0, 1, 2], inplace=True)
bank_full['month'].replace(['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], inplace=True)
bank_full['poutcome'].replace(['unknown', 'failure', 'other', 'success'], [2, 0, 3, 1], inplace=True)
bank_full['y'].replace(['no', 'yes'], [0, 1], inplace=True)

<ipython-input-13-b8edec95c237>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bank_full['job'].replace(['admin.', 'blue-collar', 'entrepreneur', 'housemaid',
<ipython-input-13-b8edec95c237>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  bank_full['job'].replace(['admin.', 'blue-collar', 'entrepreneur', 'housemaid',
<ipython-input-13-b8edec95c237>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bank_full['marital'].replace(['single', 'married', 'divorced'],[1, 2, 3], inplace=True)
<ipython-input-13-b8edec95c237>:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  bank_full['marital'].replace(['single', 'married', 'divorced'],[1, 2, 3], inplace=True)
<ipython-input-13-b8edec95c237>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bank_full['education'].replace(['tertiary', 'secondary', 'unknown', 'primary'],[3, 2, 0, 1], inplace=True)
<ipython-input-13-b8edec95c237>:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  bank_full['education'].replace(['tertiary', 'secondary', 'unknown', 'primary'],[3, 2, 0, 1], inplace=True)
<ipython-input-13-b8edec95c237>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bank_full['default'].replace(['no', 'yes'], [0, 1], inplace=True)
<ipython-input-13-b8edec95c237>:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  bank_full['default'].replace(['no', 'yes'], [0, 1], inplace=True)
<ipython-input-13-b8edec95c237>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bank_full['housing'].replace(['yes', 'no'], [1, 0], inplace=True)
<ipython-input-13-b8edec95c237>:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  bank_full['housing'].replace(['yes', 'no'], [1, 0], inplace=True)
<ipython-input-13-b8edec95c237>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bank_full['loan'].replace(['no', 'yes'], [0, 1], inplace=True)
<ipython-input-13-b8edec95c237>:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  bank_full['loan'].replace(['no', 'yes'], [0, 1], inplace=True)
<ipython-input-13-b8edec95c237>:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bank_full['contact'].replace(['unknown', 'cellular', 'telephone'], [0, 1, 2], inplace=True)
<ipython-input-13-b8edec95c237>:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  bank_full['contact'].replace(['unknown', 'cellular', 'telephone'], [0, 1, 2], inplace=True)
<ipython-input-13-b8edec95c237>:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bank_full['month'].replace(['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], inplace=True)
<ipython-input-13-b8edec95c237>:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  bank_full['month'].replace(['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], inplace=True)
<ipython-input-13-b8edec95c237>:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bank_full['poutcome'].replace(['unknown', 'failure', 'other', 'success'], [2, 0, 3, 1], inplace=True)
<ipython-input-13-b8edec95c237>:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  bank_full['poutcome'].replace(['unknown', 'failure', 'other', 'success'], [2, 0, 3, 1], inplace=True)
<ipython-input-13-b8edec95c237>:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bank_full['y'].replace(['no', 'yes'], [0, 1], inplace=True)
<ipython-input-13-b8edec95c237>:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  bank_full['y'].replace(['no', 'yes'], [0, 1], inplace=True)

In [14]:
# Verifying that variable replacement worked
print(bank_full.head())

   age  job  marital  education  default  balance  housing  loan  contact  \
0   58    5        2          3        0     2143        1     0        0
1   44   10        1          2        0       29        1     0        0
2   33    3        2          2        0        2        1     1        0
3   47    2        2          0        0     1506        1     0        0
4   33   12        1          0        0        1        0     0        0

   day  month  duration  campaign  pdays  previous  poutcome  y
0    5      5       261         1     -1         0         2  0
1    5      5       151         1     -1         0         2  0
2    5      5        76         1     -1         0         2  0
3    5      5        92         1     -1         0         2  0
4    5      5       198         1     -1         0         2  0

In [15]:
# define features and targets dataframes
X_bank_full = bank_full[['age','job','marital','education','default','balance','housing','loan','contact','day','month','duration','campaign','pdays','previous','poutcome']]
y_bank_full = bank_full[['y']]

print(X_bank_full.head())
print(y_bank_full.head())

   age  job  marital  education  default  balance  housing  loan  contact  \
0   58    5        2          3        0     2143        1     0        0
1   44   10        1          2        0       29        1     0        0
2   33    3        2          2        0        2        1     1        0
3   47    2        2          0        0     1506        1     0        0
4   33   12        1          0        0        1        0     0        0

   day  month  duration  campaign  pdays  previous  poutcome
0    5      5       261         1     -1         0         2
1    5      5       151         1     -1         0         2
2    5      5        76         1     -1         0         2
3    5      5        92         1     -1         0         2
4    5      5       198         1     -1         0         2
   y
0  0
1  0
2  0
3  0
4  0

# Decision Tree V1

In [21]:
# define features and targets dataframes
X_bank_full_V2 = bank_full[['duration','balance','age','day','month']]
y_bank_full_V2 = bank_full[['y']]

# Feature 11: Duration
# Feature 5: Balance
# Feature 0: Age
# Feature 9: Day of Week
# Feature 10: Month

In [22]:
# Divide dataset into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_bank_full_V2, y_bank_full_V2, test_size=0.33, random_state=42, stratify=y)

# Note - I don't know if this is the best split; could try a different method e.g. k-fold, but I'm starting with this

In [23]:
# Fit Decision Tree model
from sklearn.tree import DecisionTreeClassifier
tree_v1 = DecisionTreeClassifier(random_state=42)
tree_v1.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [24]:
from sklearn.metrics import classification_report
y_pred_tree = tree_v1.predict(X_test)
print(classification_report(y_test, y_pred_tree))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92     13175
           1       0.41      0.42      0.41      1745

    accuracy                           0.86     14920
   macro avg       0.67      0.67      0.67     14920
weighted avg       0.86      0.86      0.86     14920

In [25]:
from sklearn.model_selection import GridSearchCV
tree_v1.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': 42,
 'splitter': 'best'}

In [26]:
# run Grid Search with selected parameters based on get_params function above
parameters = {'max_depth':list(range(1,15)), 'min_samples_split':list(range(2,15))}
tree_v3 = GridSearchCV(tree_v1, parameters)
tree_v3.fit(X_train, y_train)
sorted(tree_v3.cv_results_.keys())
sorted(tree_v3.cv_results_.keys())

KeyboardInterrupt:

In [ ]:
# Run predictions for Decision Tree model
y_pred_tree = tree_v1.predict(X_test)

In [ ]:
tree_v3.get_params()

{'cv': None,
 'error_score': nan,
 'estimator__ccp_alpha': 0.0,
 'estimator__class_weight': None,
 'estimator__criterion': 'gini',
 'estimator__max_depth': None,
 'estimator__max_features': None,
 'estimator__max_leaf_nodes': None,
 'estimator__min_impurity_decrease': 0.0,
 'estimator__min_samples_leaf': 1,
 'estimator__min_samples_split': 2,
 'estimator__min_weight_fraction_leaf': 0.0,
 'estimator__monotonic_cst': None,
 'estimator__random_state': 42,
 'estimator__splitter': 'best',
 'estimator': DecisionTreeClassifier(random_state=42),
 'n_jobs': None,
 'param_grid': {'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
  'min_samples_split': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]},
 'pre_dispatch': '2*n_jobs',
 'refit': True,
 'return_train_score': False,
 'scoring': None,
 'verbose': 0}

In [ ]:
tree_v3_gridsearch_results = pd.DataFrame(tree_v3.cv_results_)

In [ ]:
print(tree_v3_gridsearch_results)

     mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0         0.020791      0.001565         0.008431        0.001895
1         0.021224      0.002176         0.007183        0.000278
2         0.020762      0.001546         0.007260        0.000375
3         0.021419      0.003169         0.007364        0.000956
4         0.020809      0.002618         0.006903        0.000127
..             ...           ...              ...             ...
177       0.104916      0.005500         0.005482        0.000611
178       0.102448      0.006713         0.005482        0.000386
179       0.101593      0.001352         0.005440        0.000139
180       0.102604      0.006782         0.005263        0.000090
181       0.103857      0.005283         0.005786        0.000510

     param_max_depth  param_min_samples_split  \
0                  1                        2
1                  1                        3
2                  1                        4
3                  1                        5
4                  1                        6
..               ...                      ...
177               14                       10
178               14                       11
179               14                       12
180               14                       13
181               14                       14

                                         params  split0_test_score  \
0      {'max_depth': 1, 'min_samples_split': 2}           0.882984
1      {'max_depth': 1, 'min_samples_split': 3}           0.882984
2      {'max_depth': 1, 'min_samples_split': 4}           0.882984
3      {'max_depth': 1, 'min_samples_split': 5}           0.882984
4      {'max_depth': 1, 'min_samples_split': 6}           0.882984
..                                          ...                ...
177  {'max_depth': 14, 'min_samples_split': 10}           0.879353
178  {'max_depth': 14, 'min_samples_split': 11}           0.880013
179  {'max_depth': 14, 'min_samples_split': 12}           0.879023
180  {'max_depth': 14, 'min_samples_split': 13}           0.878693
181  {'max_depth': 14, 'min_samples_split': 14}           0.880673

     split1_test_score  split2_test_score  split3_test_score  \
0             0.883130           0.882965           0.882965
1             0.883130           0.882965           0.882965
2             0.883130           0.882965           0.882965
3             0.883130           0.882965           0.882965
4             0.883130           0.882965           0.882965
..                 ...                ...                ...
177           0.882965           0.881479           0.880324
178           0.882469           0.880324           0.878838
179           0.882800           0.880819           0.880984
180           0.883625           0.883625           0.880324
181           0.883955           0.883460           0.881809

     split4_test_score  mean_test_score  std_test_score  rank_test_score
0             0.882965         0.883002        0.000065              155
1             0.882965         0.883002        0.000065              155
2             0.882965         0.883002        0.000065              155
3             0.882965         0.883002        0.000065              155
4             0.882965         0.883002        0.000065              155
..                 ...              ...             ...              ...
177           0.883955         0.881615        0.001679              178
178           0.885441         0.881417        0.002329              181
179           0.885276         0.881780        0.002117              177
180           0.884780         0.882209        0.002304              173
181           0.884285         0.882837        0.001376              169

[182 rows x 15 columns]

In [76]:
tree_v3_gridsearch_results.iloc[tree_v3_gridsearch_results['rank_test_score'].idxmin()]

mean_fit_time                                               0.070051
std_fit_time                                                0.002416
mean_score_time                                             0.006619
std_score_time                                              0.000135
param_max_depth                                                    6
param_min_samples_split                                           10
params                     {'max_depth': 6, 'min_samples_split': 10}
split0_test_score                                           0.891071
split1_test_score                                           0.893199
split2_test_score                                           0.898316
split3_test_score                                           0.893694
split4_test_score                                           0.891548
mean_test_score                                             0.893566
std_test_score                                              0.002569
rank_test_score                                                    1
Name: 73, dtype: object

In [ ]:
#Rerun model with grid search parameters
tree_v4 = DecisionTreeClassifier(random_state=42, max_depth=6, min_samples_split=10, criterion='gini')
tree_v4.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=6, min_samples_split=10, random_state=42)

In [ ]:
# Run predictions for Decision Tree model with grid search parameters
y_pred_tree_v4 = tree_v4.predict(X_test)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_tree_v4))

              precision    recall  f1-score   support

           0       0.91      0.97      0.94     13175
           1       0.57      0.26      0.36      1745

    accuracy                           0.89     14920
   macro avg       0.74      0.62      0.65     14920
weighted avg       0.87      0.89      0.87     14920

In [ ]:
from sklearn.tree import DecisionTreeClassifier
path = tree_v4.cost_complexity_pruning_path(X_train, y_train)
ccp_alphas, impurities = path.ccp_alphas, path.impurities

In [ ]:
clfs = []
for ccp_alpha in ccp_alphas:
    tree_v4 = DecisionTreeClassifier(random_state=42, ccp_alpha=ccp_alpha)
    tree_v4.fit(X_train, y_train)
    clfs.append(tree_v4)
print(
    "Number of nodes in the last tree is: {} with ccp_alpha: {}".format(
        clfs[-1].tree_.node_count, ccp_alphas[-1]
    )
)

Number of nodes in the last tree is: 1 with ccp_alpha: 0.026515727896081143

In [ ]:
print(ccp_alphas)
print(impurities)

[0.00000000e+00 1.62064340e-05 1.64027383e-05 ... 4.08816690e-03
 4.69947476e-03 2.65157279e-02]
[0.00000000e+00 6.48257358e-05 1.30436689e-04 ... 1.75404420e-01
 1.80103895e-01 2.06619623e-01]

In [ ]:
tree_v5 = DecisionTreeClassifier(random_state=42,criterion = 'gini', max_depth=6, min_samples_split=10)
tree_v5.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=6, min_samples_split=10, random_state=42)

# Decision Tree V2

In [16]:
# Select features based on exploratory data analysis
X_bank_full_V3 = bank_full[['age','housing','month','duration','pdays','poutcome']]
y_bank_full_V3 = bank_full[['y']]

In [17]:
# Divide dataset into training and test sets -- adjusting to 20% test set
from sklearn.model_selection import train_test_split
X_train_V3, X_test_V3, y_train_V3, y_test_V3 = train_test_split(X_bank_full_V3, y_bank_full_V3, test_size=0.20, random_state=42, stratify=y)

In [27]:
# Conduct grid search
from sklearn.model_selection import GridSearchCV
parameters = {'max_depth':list(range(1,30,2)), 'min_samples_split':list(range(2,30,2)), 'min_samples_leaf':list(range(2,20,2))}
tree_v6 = GridSearchCV(tree_v1, param_grid=parameters, scoring='recall')
tree_v6.fit(X_train_V3, y_train_V3)
sorted(tree_v6.cv_results_.keys())

['mean_fit_time',
 'mean_score_time',
 'mean_test_score',
 'param_max_depth',
 'param_min_samples_leaf',
 'param_min_samples_split',
 'params',
 'rank_test_score',
 'split0_test_score',
 'split1_test_score',
 'split2_test_score',
 'split3_test_score',
 'split4_test_score',
 'std_fit_time',
 'std_score_time',
 'std_test_score']

In [28]:
# Convert gridsearch results to dataframe
tree_v6_gridsearch_results = pd.DataFrame(tree_v6.cv_results_)

In [29]:
# Display gridsearch results
from IPython.display import display
import pandas as pd
display(tree_v6_gridsearch_results)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_min_samples_leaf,param_min_samples_split,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.015207,0.002058,0.009343,0.000488,1,2,2,"{'max_depth': 1, 'min_samples_leaf': 2, 'min_s...",0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1765
1,0.013106,0.000611,0.008292,0.000361,1,2,4,"{'max_depth': 1, 'min_samples_leaf': 2, 'min_s...",0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1765
2,0.012404,0.000651,0.008365,0.000598,1,2,6,"{'max_depth': 1, 'min_samples_leaf': 2, 'min_s...",0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1765
3,0.012417,0.000594,0.008205,0.000241,1,2,8,"{'max_depth': 1, 'min_samples_leaf': 2, 'min_s...",0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1765
4,0.012358,0.000626,0.009022,0.001398,1,2,10,"{'max_depth': 1, 'min_samples_leaf': 2, 'min_s...",0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1885,0.071243,0.001963,0.010478,0.000744,29,18,20,"{'max_depth': 29, 'min_samples_leaf': 18, 'min...",0.394799,0.364066,0.415584,0.41253,0.444444,0.406285,0.026442,1025
1886,0.072514,0.004823,0.009847,0.000230,29,18,22,"{'max_depth': 29, 'min_samples_leaf': 18, 'min...",0.394799,0.364066,0.415584,0.41253,0.444444,0.406285,0.026442,1025
1887,0.069448,0.002591,0.009038,0.000361,29,18,24,"{'max_depth': 29, 'min_samples_leaf': 18, 'min...",0.394799,0.364066,0.415584,0.41253,0.444444,0.406285,0.026442,1025
1888,0.068433,0.001149,0.009264,0.000310,29,18,26,"{'max_depth': 29, 'min_samples_leaf': 18, 'min...",0.394799,0.364066,0.415584,0.41253,0.444444,0.406285,0.026442,1025
1889,0.069425,0.002953,0.009039,0.000195,29,18,28,"{'max_depth': 29, 'min_samples_leaf': 18, 'min...",0.394799,0.364066,0.415584,0.41253,0.444444,0.406285,0.026442,1025

In [30]:
# Identify gridsearch result with best mean recall score
tree_v6_gridsearch_results.iloc[tree_v6_gridsearch_results['rank_test_score'].idxmin()]

# Appears to be max_depth=17 and min_samples_split = 2, and min_samples_leaf=24 with 43% mean recall score
print(tree_v6_gridsearch_results.iloc[tree_v6_gridsearch_results['rank_test_score'].idxmin()])

mean_fit_time                                                       0.080381
std_fit_time                                                        0.005857
mean_score_time                                                     0.009016
std_score_time                                                      0.000081
param_max_depth                                                           17
param_min_samples_leaf                                                     2
param_min_samples_split                                                   24
params                     {'max_depth': 17, 'min_samples_leaf': 2, 'min_...
split0_test_score                                                   0.437352
split1_test_score                                                   0.381797
split2_test_score                                                   0.416765
split3_test_score                                                   0.445626
split4_test_score                                                   0.473995
mean_test_score                                                     0.431107
std_test_score                                                      0.030745
rank_test_score                                                            1
Name: 1019, dtype: object

In [31]:
# Fit Decision Tree model
from sklearn.tree import DecisionTreeClassifier
tree_v6 = DecisionTreeClassifier(random_state=42, max_depth=17, min_samples_split=2, min_samples_leaf=24, criterion='gini')
tree_v6.fit(X_train_V3, y_train_V3)

DecisionTreeClassifier(max_depth=17, min_samples_leaf=24, random_state=42)

In [32]:
# Run predictions for Decision Tree model with grid search parameters
y_pred_tree_v6 = tree_v6.predict(X_test_V3)

from sklearn.metrics import classification_report
print(classification_report(y_test_V3, y_pred_tree_v6))

              precision    recall  f1-score   support

           0       0.93      0.96      0.94      7985
           1       0.59      0.42      0.49      1058

    accuracy                           0.90      9043
   macro avg       0.76      0.69      0.71      9043
weighted avg       0.89      0.90      0.89      9043

# Decision Tree_Lower Decision Threshold

In [40]:
# Set lower decision threshold
from sklearn.model_selection import FixedThresholdClassifier
tree_v6_lower_threshold = FixedThresholdClassifier(tree_v6, threshold=0.25, response_method="predict_proba").fit(X_train_V3, y_train_V3)

In [41]:
# Run predictions for decision tree with lowered threshold
y_pred_tree_lthresh = tree_v6_lower_threshold.predict(X_test_V3)

print(classification_report(y_test_V3, y_pred_tree_lthresh))

              precision    recall  f1-score   support

           0       0.96      0.89      0.92      7985
           1       0.46      0.70      0.56      1058

    accuracy                           0.87      9043
   macro avg       0.71      0.80      0.74      9043
weighted avg       0.90      0.87      0.88      9043